prog:player.o main.o perso.o
	gcc player.o main.o perso.o -o prog -lSDL -lSDL_ttf -lSDL_mixer -lSDL_image
main.o:main.c
	gcc -c main.c
player.o:player.c
	gcc -c player.c
perso.o:perso.c
	gcc -c perso.c
